### ISSUE TITLE
Errors reporting that maps aren't valid CSS values

### ISSUE THREAD

**Issue by quasipickle** [plentycode/sass-export#74]
I have a file with nothing but variables that I'm trying to export.  The file compiles to CSS with no errors, but when I try to `sass-export` the file, I get errors that a couple maps I've defined aren't valid CSS values - even though I've not tried to treat them as CSS values at all.

## SASS file

```scss
@use "sass:map";

@import "variables.scss";
@import "../node_modules/bootstrap/scss/_functions";
@import "../node_modules/bootstrap/scss/_variables";

$levels: (100: 80%,
          200: 60%,
          300: 40%,
          400: 20%,
          500: 0,
          600: 20%,
          700: 40%,
          800: 60%,
          900: 80%);

 /**
 * @sass-export-section="palette"
 */
$palette: (grays:$grays);

@each $label, $base in $theme-colors {
    $steps: ();
    @each $step, $amount in $levels{
        $adjusted: if($step < 500, tint-color($base,$amount), shade-color($base,$amount));
        $text: color-contrast($adjusted);
        $step-colors:("background": $adjusted, "text": $text);
        $steps: map.merge($steps,($step:$step-colors));
    }
    $palette: map.merge($palette, ($label:$steps));
}
//@end-sass-export-section
```
## Shell command
```sh
sass-export scss/_dv-palette-export.scss -o docs-source/data/palette.json -d "scss/"
```
## Errors
```
Error: (100: 80%, 200: 60%, 300: 40%, 400: 20%, 500: 0, 600: 20%, 700: 40%, 800: 60%, 900: 80%) isn't a valid CSS value.
   ╷
38 │ #sass-export-id.levels{content:"#{(100: 80%, 200: 60%, 300: 40%, 400: 20%, 500: 0, 600: 20%, 700: 40%, 800: 60%, 900: 80%)}";}
   │                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  stdin 38:35  root stylesheet
    at Object.wrapException (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:1246:17)
    at _SerializeVisitor0.visitMap$1 (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:90447:17)
    at SassMap0.accept$1$1 (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:85858:22)
    at SassMap0.accept$1 (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:85861:19)
    at Object.serializeValue0 (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:21614:13)
    at _EvaluateVisitor__serialize_closure1.call$0 (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:81900:16)
    at _EvaluateVisitor1._evaluate0$_addExceptionSpan$1$2 (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:80347:23)
    at _EvaluateVisitor1._evaluate0$_addExceptionSpan$2 (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:80368:19)
    at _EvaluateVisitor1._evaluate0$_serialize$3$quote (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:80180:19)
    at _EvaluateVisitor_visitStringExpression_closure1.call$1 (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:81752:75) {
  formatted: "Error: (100: 80%, 200: 60%, 300: 40%, 400: 20%, 500: 0, 600: 20%, 700: 40%, 800: 60%, 900: 80%) isn't a valid CSS value.\n" +
    '   ╷\n' +
    '38 │ #sass-export-id.levels{content:"#{(100: 80%, 200: 60%, 300: 40%, 400: 20%, 500: 0, 600: 20%, 700: 40%, 800: 60%, 900: 80%)}";}\n' +
    '   │                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
    '   ╵\n' +
    '  stdin 38:35  root stylesheet',
  line: 38,
  column: 35,
  file: 'stdin',
  status: 1
}
Error: () isn't a valid CSS value.
   ╷
38 │ #sass-export-id.steps{content:"#{()}";}
   │                                  ^^
   ╵
  stdin 38:34  root stylesheet
    at Object.wrapException (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:1246:17)
    at _SerializeVisitor0.visitList$1 (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:90383:19)
    at SassList0.accept$1$1 (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:85340:22)
    at SassList0.accept$1 (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:85343:19)
    at Object.serializeValue0 (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:21614:13)
    at _EvaluateVisitor__serialize_closure1.call$0 (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:81900:16)
    at _EvaluateVisitor1._evaluate0$_addExceptionSpan$1$2 (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:80347:23)
    at _EvaluateVisitor1._evaluate0$_addExceptionSpan$2 (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:80368:19)
    at _EvaluateVisitor1._evaluate0$_serialize$3$quote (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:80180:19)
    at _EvaluateVisitor_visitStringExpression_closure1.call$1 (/home/myusername/.nvm/versions/node/v17.4.0/lib/node_modules/sass-export/node_modules/sass/sass.dart.js:81752:75) {
  formatted: "Error: () isn't a valid CSS value.\n" +
    '   ╷\n' +
    '38 │ #sass-export-id.steps{content:"#{()}";}\n' +
    '   │                                  ^^\n' +
    '   ╵\n' +
    '  stdin 38:34  root stylesheet',
  line: 38,
  column: 34,
  file: 'stdin',
  status: 1
}
```
## Generated JSON
```json
{
  "variables": [
    {
      "name": "$levels",
      "value": "(100: 80%, 200: 60%, 300: 40%, 400: 20%, 500: 0, 600: 20%, 700: 40%, 800: 60%, 900: 80%)",
      "compiledValue": ""
    }
  ],
  "palette": [
    {
      "name": "$palette",
      "value": "(grays:$grays)",
      "mapValue": [
        {
          "name": "grays",
          "value": "$grays",
          "compiledValue": "(\"100\": #f8f9fa, \"200\": #e9ecef, \"300\": #dee2e6, \"400\": #ced4da, \"500\": #adb5bd, \"600\": #6c757d, \"700\": #495057, \"800\": #343a40, \"900\": #212529)"
        }
      ],
      "compiledValue": "(grays: (\"100\": #f8f9fa, \"200\": #e9ecef, \"300\": #dee2e6, \"400\": #ced4da, \"500\": #adb5bd, \"600\": #6c757d, \"700\": #495057, \"800\": #343a40, \"900\": #212529))"
    },
    {
      "name": "$steps",
      "value": "()",
      "compiledValue": "()"
    }
  ]
}
```

Possibly related, but you can see that pallete > grays does not have a `mapValue` element.
